services:
  ip_updater:
    image: cristiancapsuna/ip_updater:latest
    deploy:
      restart_policy:
        condition: none
    secrets:
      - ip_updater_key
    configs:
      - ip_updater_ccapsuna_record
      - ip_updater_ccapsuna_zone
      - ip_updater_filotimocreations_record
      - ip_updater_filotimocreations_zone
    environment:
      - KEY_PATH="/run/secrets/ip_updater_key"
      - CCAPSUNA_ZONE_PATH="/ip_updater_ccapsuna_zone"
      - CCAPSUNA_RECORD_PATH="/ip_updater_ccapsuna_record"
      - FILOTIMOCREATIONS_ZONE_PATH="/ip_updater_filotimocreations_zone"
      - FILOTIMOCREATIONS_RECORD_PATH="/ip_updater_filotimocreations_record"

secrets:
  ip_updater_key:
    external: true

configs:
  ip_updater_ccapsuna_record:
    external: true
  ip_updater_ccapsuna_zone:
    external: true
  ip_updater_filotimocreations_record:
    external: true
  ip_updater_filotimocreations_zone:
    external: true
