name: build-and-move-binary

on:
  push:
    branches: ["main"]

env:
  cargo_term_color: always

jobs:
  build-and-move:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Add rust toolchain to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Build
      run: cargo build --release
    - name: Move
      run: mv target/release/${{ github.event.repository.name }} /opt/bin
